// GENERATED by scripts/build-geo.mjs — do not edit by hand.
// Sources: geoalgeria@1.2.0 cross-checked against algeria-wilayas-communes@1.0.0.
// Legal basis: loi n° 26-06 (JO n°25, 5 April 2026) — 69 wilayas, 1541 communes.

export type Wilaya = {
  /** 1–69 under the current law. */
  code: number;
  /** The pre-2026 parent wilaya (1–58). Equal to `code` for the original 58. */
  code58: number;
  nameAr: string;
  nameFr: string;
  /** URL identifier — stable across administrative reshuffles. */
  slug: string;
  /** Alternate spellings and the parent name, for the search box. */
  aliases: string[];
  isNew2026: boolean;
  communeCount: number;
};

export const kWilayas: Wilaya[] = [
  {
    "code": 1,
    "code58": 1,
    "nameAr": "أدرار",
    "nameFr": "Adrar",
    "slug": "adrar",
    "aliases": [
      "01"
    ],
    "isNew2026": false,
    "communeCount": 16
  },
  {
    "code": 2,
    "code58": 2,
    "nameAr": "الشلف",
    "nameFr": "Chlef",
    "slug": "chlef",
    "aliases": [
      "02"
    ],
    "isNew2026": false,
    "communeCount": 35
  },
  {
    "code": 3,
    "code58": 3,
    "nameAr": "الأغواط",
    "nameFr": "Laghouat",
    "slug": "laghouat",
    "aliases": [
      "03"
    ],
    "isNew2026": false,
    "communeCount": 12
  },
  {
    "code": 4,
    "code58": 4,
    "nameAr": "أم البواقي",
    "nameFr": "Oum El Bouaghi",
    "slug": "oum-el-bouaghi",
    "aliases": [
      "04"
    ],
    "isNew2026": false,
    "communeCount": 29
  },
  {
    "code": 5,
    "code58": 5,
    "nameAr": "باتنة",
    "nameFr": "Batna",
    "slug": "batna",
    "aliases": [
      "05"
    ],
    "isNew2026": false,
    "communeCount": 53
  },
  {
    "code": 6,
    "code58": 6,
    "nameAr": "بجاية",
    "nameFr": "Béjaïa",
    "slug": "bejaia",
    "aliases": [
      "06"
    ],
    "isNew2026": false,
    "communeCount": 52
  },
  {
    "code": 7,
    "code58": 7,
    "nameAr": "بسكرة",
    "nameFr": "Biskra",
    "slug": "biskra",
    "aliases": [
      "07"
    ],
    "isNew2026": false,
    "communeCount": 22
  },
  {
    "code": 8,
    "code58": 8,
    "nameAr": "بشار",
    "nameFr": "Béchar",
    "slug": "bechar",
    "aliases": [
      "08"
    ],
    "isNew2026": false,
    "communeCount": 12
  },
  {
    "code": 9,
    "code58": 9,
    "nameAr": "البليدة",
    "nameFr": "Blida",
    "slug": "blida",
    "aliases": [
      "09"
    ],
    "isNew2026": false,
    "communeCount": 25
  },
  {
    "code": 10,
    "code58": 10,
    "nameAr": "البويرة",
    "nameFr": "Bouira",
    "slug": "bouira",
    "aliases": [
      "10"
    ],
    "isNew2026": false,
    "communeCount": 45
  },
  {
    "code": 11,
    "code58": 11,
    "nameAr": "تمنراست",
    "nameFr": "Tamanrasset",
    "slug": "tamanrasset",
    "aliases": [
      "11"
    ],
    "isNew2026": false,
    "communeCount": 5
  },
  {
    "code": 12,
    "code58": 12,
    "nameAr": "تبسة",
    "nameFr": "Tébessa",
    "slug": "tebessa",
    "aliases": [
      "12"
    ],
    "isNew2026": false,
    "communeCount": 24
  },
  {
    "code": 13,
    "code58": 13,
    "nameAr": "تلمسان",
    "nameFr": "Tlemcen",
    "slug": "tlemcen",
    "aliases": [
      "13"
    ],
    "isNew2026": false,
    "communeCount": 49
  },
  {
    "code": 14,
    "code58": 14,
    "nameAr": "تيارت",
    "nameFr": "Tiaret",
    "slug": "tiaret",
    "aliases": [
      "14"
    ],
    "isNew2026": false,
    "communeCount": 36
  },
  {
    "code": 15,
    "code58": 15,
    "nameAr": "تيزي وزو",
    "nameFr": "Tizi Ouzou",
    "slug": "tizi-ouzou",
    "aliases": [
      "15"
    ],
    "isNew2026": false,
    "communeCount": 67
  },
  {
    "code": 16,
    "code58": 16,
    "nameAr": "الجزائر",
    "nameFr": "Alger",
    "slug": "alger",
    "aliases": [
      "16",
      "algiers"
    ],
    "isNew2026": false,
    "communeCount": 57
  },
  {
    "code": 17,
    "code58": 17,
    "nameAr": "الجلفة",
    "nameFr": "Djelfa",
    "slug": "djelfa",
    "aliases": [
      "17"
    ],
    "isNew2026": false,
    "communeCount": 18
  },
  {
    "code": 18,
    "code58": 18,
    "nameAr": "جيجل",
    "nameFr": "Jijel",
    "slug": "jijel",
    "aliases": [
      "18"
    ],
    "isNew2026": false,
    "communeCount": 28
  },
  {
    "code": 19,
    "code58": 19,
    "nameAr": "سطيف",
    "nameFr": "Sétif",
    "slug": "setif",
    "aliases": [
      "19"
    ],
    "isNew2026": false,
    "communeCount": 60
  },
  {
    "code": 20,
    "code58": 20,
    "nameAr": "سعيدة",
    "nameFr": "Saïda",
    "slug": "saida",
    "aliases": [
      "20"
    ],
    "isNew2026": false,
    "communeCount": 16
  },
  {
    "code": 21,
    "code58": 21,
    "nameAr": "سكيكدة",
    "nameFr": "Skikda",
    "slug": "skikda",
    "aliases": [
      "21"
    ],
    "isNew2026": false,
    "communeCount": 38
  },
  {
    "code": 22,
    "code58": 22,
    "nameAr": "سيدي بلعباس",
    "nameFr": "Sidi Bel Abbès",
    "slug": "sidi-bel-abbes",
    "aliases": [
      "22"
    ],
    "isNew2026": false,
    "communeCount": 52
  },
  {
    "code": 23,
    "code58": 23,
    "nameAr": "عنابة",
    "nameFr": "Annaba",
    "slug": "annaba",
    "aliases": [
      "23"
    ],
    "isNew2026": false,
    "communeCount": 12
  },
  {
    "code": 24,
    "code58": 24,
    "nameAr": "قالمة",
    "nameFr": "Guelma",
    "slug": "guelma",
    "aliases": [
      "24"
    ],
    "isNew2026": false,
    "communeCount": 34
  },
  {
    "code": 25,
    "code58": 25,
    "nameAr": "قسنطينة",
    "nameFr": "Constantine",
    "slug": "constantine",
    "aliases": [
      "25"
    ],
    "isNew2026": false,
    "communeCount": 12
  },
  {
    "code": 26,
    "code58": 26,
    "nameAr": "المدية",
    "nameFr": "Médéa",
    "slug": "medea",
    "aliases": [
      "26"
    ],
    "isNew2026": false,
    "communeCount": 43
  },
  {
    "code": 27,
    "code58": 27,
    "nameAr": "مستغانم",
    "nameFr": "Mostaganem",
    "slug": "mostaganem",
    "aliases": [
      "27"
    ],
    "isNew2026": false,
    "communeCount": 32
  },
  {
    "code": 28,
    "code58": 28,
    "nameAr": "المسيلة",
    "nameFr": "M'sila",
    "slug": "msila",
    "aliases": [
      "28"
    ],
    "isNew2026": false,
    "communeCount": 24
  },
  {
    "code": 29,
    "code58": 29,
    "nameAr": "معسكر",
    "nameFr": "Mascara",
    "slug": "mascara",
    "aliases": [
      "29"
    ],
    "isNew2026": false,
    "communeCount": 47
  },
  {
    "code": 30,
    "code58": 30,
    "nameAr": "ورقلة",
    "nameFr": "Ouargla",
    "slug": "ouargla",
    "aliases": [
      "30"
    ],
    "isNew2026": false,
    "communeCount": 8
  },
  {
    "code": 31,
    "code58": 31,
    "nameAr": "وهران",
    "nameFr": "Oran",
    "slug": "oran",
    "aliases": [
      "31"
    ],
    "isNew2026": false,
    "communeCount": 26
  },
  {
    "code": 32,
    "code58": 32,
    "nameAr": "البيض",
    "nameFr": "El Bayadh",
    "slug": "el-bayadh",
    "aliases": [
      "32"
    ],
    "isNew2026": false,
    "communeCount": 15
  },
  {
    "code": 33,
    "code58": 33,
    "nameAr": "إليزي",
    "nameFr": "Illizi",
    "slug": "illizi",
    "aliases": [
      "33"
    ],
    "isNew2026": false,
    "communeCount": 4
  },
  {
    "code": 34,
    "code58": 34,
    "nameAr": "برج بوعريريج",
    "nameFr": "Bordj Bou Arreridj",
    "slug": "bordj-bou-arreridj",
    "aliases": [
      "34"
    ],
    "isNew2026": false,
    "communeCount": 34
  },
  {
    "code": 35,
    "code58": 35,
    "nameAr": "بومرداس",
    "nameFr": "Boumerdès",
    "slug": "boumerdes",
    "aliases": [
      "35"
    ],
    "isNew2026": false,
    "communeCount": 32
  },
  {
    "code": 36,
    "code58": 36,
    "nameAr": "الطارف",
    "nameFr": "El Tarf",
    "slug": "el-tarf",
    "aliases": [
      "36"
    ],
    "isNew2026": false,
    "communeCount": 24
  },
  {
    "code": 37,
    "code58": 37,
    "nameAr": "تندوف",
    "nameFr": "Tindouf",
    "slug": "tindouf",
    "aliases": [
      "37"
    ],
    "isNew2026": false,
    "communeCount": 2
  },
  {
    "code": 38,
    "code58": 38,
    "nameAr": "تيسمسيلت",
    "nameFr": "Tissemsilt",
    "slug": "tissemsilt",
    "aliases": [
      "38"
    ],
    "isNew2026": false,
    "communeCount": 22
  },
  {
    "code": 39,
    "code58": 39,
    "nameAr": "الوادي",
    "nameFr": "El Oued",
    "slug": "el-oued",
    "aliases": [
      "39"
    ],
    "isNew2026": false,
    "communeCount": 22
  },
  {
    "code": 40,
    "code58": 40,
    "nameAr": "خنشلة",
    "nameFr": "Khenchela",
    "slug": "khenchela",
    "aliases": [
      "40"
    ],
    "isNew2026": false,
    "communeCount": 21
  },
  {
    "code": 41,
    "code58": 41,
    "nameAr": "سوق أهراس",
    "nameFr": "Souk Ahras",
    "slug": "souk-ahras",
    "aliases": [
      "41"
    ],
    "isNew2026": false,
    "communeCount": 26
  },
  {
    "code": 42,
    "code58": 42,
    "nameAr": "تيبازة",
    "nameFr": "Tipaza",
    "slug": "tipaza",
    "aliases": [
      "42"
    ],
    "isNew2026": false,
    "communeCount": 28
  },
  {
    "code": 43,
    "code58": 43,
    "nameAr": "ميلة",
    "nameFr": "Mila",
    "slug": "mila",
    "aliases": [
      "43"
    ],
    "isNew2026": false,
    "communeCount": 32
  },
  {
    "code": 44,
    "code58": 44,
    "nameAr": "عين الدفلى",
    "nameFr": "Aïn Defla",
    "slug": "ain-defla",
    "aliases": [
      "44"
    ],
    "isNew2026": false,
    "communeCount": 36
  },
  {
    "code": 45,
    "code58": 45,
    "nameAr": "النعامة",
    "nameFr": "Naâma",
    "slug": "naama",
    "aliases": [
      "45"
    ],
    "isNew2026": false,
    "communeCount": 12
  },
  {
    "code": 46,
    "code58": 46,
    "nameAr": "عين تموشنت",
    "nameFr": "Aïn Témouchent",
    "slug": "ain-temouchent",
    "aliases": [
      "46"
    ],
    "isNew2026": false,
    "communeCount": 28
  },
  {
    "code": 47,
    "code58": 47,
    "nameAr": "غرداية",
    "nameFr": "Ghardaïa",
    "slug": "ghardaia",
    "aliases": [
      "47"
    ],
    "isNew2026": false,
    "communeCount": 10
  },
  {
    "code": 48,
    "code58": 48,
    "nameAr": "غليزان",
    "nameFr": "Relizane",
    "slug": "relizane",
    "aliases": [
      "48"
    ],
    "isNew2026": false,
    "communeCount": 38
  },
  {
    "code": 49,
    "code58": 49,
    "nameAr": "تيميمون",
    "nameFr": "Timimoun",
    "slug": "timimoun",
    "aliases": [
      "49"
    ],
    "isNew2026": false,
    "communeCount": 10
  },
  {
    "code": 50,
    "code58": 50,
    "nameAr": "برج باجي مختار",
    "nameFr": "Bordj Badji Mokhtar",
    "slug": "bordj-badji-mokhtar",
    "aliases": [
      "50"
    ],
    "isNew2026": false,
    "communeCount": 2
  },
  {
    "code": 51,
    "code58": 51,
    "nameAr": "أولاد جلال",
    "nameFr": "Ouled Djellal",
    "slug": "ouled-djellal",
    "aliases": [
      "51"
    ],
    "isNew2026": false,
    "communeCount": 6
  },
  {
    "code": 52,
    "code58": 52,
    "nameAr": "بني عباس",
    "nameFr": "Béni Abbès",
    "slug": "beni-abbes",
    "aliases": [
      "52"
    ],
    "isNew2026": false,
    "communeCount": 9
  },
  {
    "code": 53,
    "code58": 53,
    "nameAr": "عين صالح",
    "nameFr": "In Salah",
    "slug": "in-salah",
    "aliases": [
      "53"
    ],
    "isNew2026": false,
    "communeCount": 3
  },
  {
    "code": 54,
    "code58": 54,
    "nameAr": "عين قزام",
    "nameFr": "In Guezzam",
    "slug": "in-guezzam",
    "aliases": [
      "54"
    ],
    "isNew2026": false,
    "communeCount": 2
  },
  {
    "code": 55,
    "code58": 55,
    "nameAr": "توقرت",
    "nameFr": "Touggourt",
    "slug": "touggourt",
    "aliases": [
      "55"
    ],
    "isNew2026": false,
    "communeCount": 13
  },
  {
    "code": 56,
    "code58": 56,
    "nameAr": "جانت",
    "nameFr": "Djanet",
    "slug": "djanet",
    "aliases": [
      "56"
    ],
    "isNew2026": false,
    "communeCount": 2
  },
  {
    "code": 57,
    "code58": 57,
    "nameAr": "المغير",
    "nameFr": "El M'Ghair",
    "slug": "el-mghair",
    "aliases": [
      "57"
    ],
    "isNew2026": false,
    "communeCount": 8
  },
  {
    "code": 58,
    "code58": 58,
    "nameAr": "المنيعة",
    "nameFr": "El Meniaa",
    "slug": "el-meniaa",
    "aliases": [
      "58"
    ],
    "isNew2026": false,
    "communeCount": 3
  },
  {
    "code": 59,
    "code58": 3,
    "nameAr": "آفلو",
    "nameFr": "Aflou",
    "slug": "aflou",
    "aliases": [
      "59",
      "laghouat"
    ],
    "isNew2026": true,
    "communeCount": 12
  },
  {
    "code": 60,
    "code58": 5,
    "nameAr": "بريكة",
    "nameFr": "Barika",
    "slug": "barika",
    "aliases": [
      "60",
      "batna"
    ],
    "isNew2026": true,
    "communeCount": 8
  },
  {
    "code": 61,
    "code58": 7,
    "nameAr": "القنطرة",
    "nameFr": "El Kantara",
    "slug": "el-kantara",
    "aliases": [
      "61",
      "biskra"
    ],
    "isNew2026": true,
    "communeCount": 5
  },
  {
    "code": 62,
    "code58": 12,
    "nameAr": "بئر العاتر",
    "nameFr": "Bir El Ater",
    "slug": "bir-el-ater",
    "aliases": [
      "62",
      "tebessa"
    ],
    "isNew2026": true,
    "communeCount": 4
  },
  {
    "code": 63,
    "code58": 13,
    "nameAr": "العريشة",
    "nameFr": "El Aricha",
    "slug": "el-aricha",
    "aliases": [
      "63",
      "tlemcen"
    ],
    "isNew2026": true,
    "communeCount": 4
  },
  {
    "code": 64,
    "code58": 14,
    "nameAr": "قصر الشلالة",
    "nameFr": "Ksar Chellala",
    "slug": "ksar-chellala",
    "aliases": [
      "64",
      "tiaret"
    ],
    "isNew2026": true,
    "communeCount": 6
  },
  {
    "code": 65,
    "code58": 17,
    "nameAr": "عين وسارة",
    "nameFr": "Aïn Oussera",
    "slug": "ain-oussera",
    "aliases": [
      "65",
      "ain-oussara",
      "djelfa"
    ],
    "isNew2026": true,
    "communeCount": 10
  },
  {
    "code": 66,
    "code58": 17,
    "nameAr": "مسعد",
    "nameFr": "Messaad",
    "slug": "messaad",
    "aliases": [
      "66",
      "djelfa"
    ],
    "isNew2026": true,
    "communeCount": 8
  },
  {
    "code": 67,
    "code58": 26,
    "nameAr": "قصر البخاري",
    "nameFr": "Ksar El Boukhari",
    "slug": "ksar-el-boukhari",
    "aliases": [
      "67",
      "medea"
    ],
    "isNew2026": true,
    "communeCount": 21
  },
  {
    "code": 68,
    "code58": 28,
    "nameAr": "بوسعادة",
    "nameFr": "Bou Saâda",
    "slug": "bou-saada",
    "aliases": [
      "68",
      "msila"
    ],
    "isNew2026": true,
    "communeCount": 23
  },
  {
    "code": 69,
    "code58": 32,
    "nameAr": "الأبيض سيدي الشيخ",
    "nameFr": "El Abiodh Sidi Cheikh",
    "slug": "el-abiodh-sidi-cheikh",
    "aliases": [
      "69",
      "el-bayadh"
    ],
    "isNew2026": true,
    "communeCount": 7
  }
];

export const kWilayaBySlug = new Map(kWilayas.map((w) => [w.slug, w]));
export const kWilayaByCode = new Map(kWilayas.map((w) => [w.code, w]));
